### ISSUE TITLE
Use versions and gopkg

### ISSUE THREAD

**Issue by mcuadros** [thcyron/sqlbuilder#1]
I am user of this library and since the change of the query args and query, my app was broken. 

Will be awesome if you can tag de versions when the API changes and use [gopkg.in](http://labix.org/gopkg.in), this will make the people happier

Regards!

**Comment by thcyron** [comment]
Yes, you’re right. I’ll release a 1.0 version and stop making breaking changes after then.

**Comment by mcuadros** [comment]
really appreciated!

**Comment by thcyron** [comment]
I’ve released and tagged v1.0.0.
